language: ruby

rvm:
  - 2.4.1

sudo: false

cache:
  bundler: true

services:
  - postgresql

env:
  global:
    - CI=true
    - RAILS_ENV=test

  matrix:
    - "DB=sqlite3"
    - "DB=postgresql"

before_script:
  - cp spec/test_app/config/database.$DB.yml.travis spec/test_app/config/database.yml
